language: clojure
jdk:
- openjdk8
services:
- docker
sudo: required
before_install:
- make checkdeps
- make runtests
after_success:
- "./bin/build"
notifications:
  slack:
    rooms:
    - lcmap:UTqlh9PfPVomfpli10WKyZoh#cicd
env:
  global:
  - secure: q4E1/lGhFb7kqq+7Oql46oPwVXlIY7Rkrv1wDX104t+SLn/Y+WtyQey6F0NN1EIVmHze+XQLTwMEVvjcjR65knbXz9xBiOpDyIlC0YPCrm1K/9Z3M3pasbHVV3MRkMeN/rsY9+XB7tvW14WS6FtjO/K3DePE0erih4nSikT8q5zXEyxzkyGuihXyiDZpHPIX6lSoorx8bjNABoVdWVCNBtkYXrQc6ztEwy4R7OzmBBV918mRGMuvcHfGCAHOi4inaaWSHTvezynyg/sLyFtCWUqoc5VtFKUHrY6DwqVcd1mAAf3oUHSytX49p4H+nWLvX7hWS8mjy+Wft078hVGizOcILLaV8uarVdTBooQtAp+9a9h9OZCn8KKBTJpvIQoyUaAUp3sKGX2BcLnQdr+ft0SfpwZKDu9v2YLvhlWvIJq+YwgCXmckL4Atfu9fvcc54Dld9wD+F680HnD6rzaD5J+BsAHuguoWw8rPKJjDdjTYHATA5xOvFJb8/UhnUSyrkMZFpQxpvg+nis3m59Mu216KyN3bhKcCs2ZzUpESFdo4JK8XSuz5ETdR9wMIZ77UhL02Mk3sldWIoryNiXzscL55FsY02svOt85dEDCMNWVnl20dbA9kvxS3ck1NLRRHAxg5Q8dtM+2qbX+zlKCMzNw8/bckDvzCClTPi5Aszio=
  - secure: Zvwgeg3mjKAe2IjRRU4ugIBiFrPmWDyEXCXkLZK+GSVQfYC7O+sSIsBnCBx/G0hADCxTEgGNUL9btt1eyx+qxyO3qyLm9UhAUDOx1ztSczImO9hgXM+vxjRvwDNNRC+nv+QPPBqpor85Ae0pvvj7ZcP7gv8UUliZ2B/HpxOrHK2stE4MrHtDszsbgC4wvnTXvGqShZGbHz6g1Mnb0HeO7ChsE20amvJjGkfA33TD/tbJELco/8DVczoNRSUIHSoX1d8B+MgPXFrWuwggE3jsjapsQED8T3LhJAp599yjWGLWESJ84w7yQhLvaDfNOikCcZOHOqRjQb5okmpOaR5RttexHt0dOiMOJy6jeUatMXfgJAsIKzaEDXY+qqsj7JL8I7d3sLdqKlTrkpLdODuBssrs4HHncbrvjeoFJDcpdawQbPpbAce6TxFm7pd/JZ2zV363Xa2gX+1vm78vxFAs56DCN+wxbeQHbmBlaLNRRNAOInVdU8tMxkgo43J1KHK8vgun5t9I0u6POp+fk5JAOm8ZwnK6cr4HlZ25VZbXlAQBcxXeKXWX1PcgAojlJZpNMl1bPBHPRKitRrGmG5PT9f9q40Zsdhe3yhnWYQEDd61ppNAYgMErZ/Yy0YoyLIG4EDeLgsr8hfadybeWyIIlqBB6O7WPRPsrTRp8pXOG8SQ=
